export const PHASES = ['JS1', 'JS2'] as const

export const LOCATION_TYPES = ['Project Office', 'Site - Comm', 'Site - Const'] as const

export const FUNCTIONAL_GROUPS = [
  'Project Management',
  'Engineering',
  'Contracts & Procurement',
  'Construction Management',
  'Commissioning',
  'Project Controls',
  'Project Services',
] as const

export const DSG_OPTIONS = [
  '100 - Project Management (incl. Project Sponsor)',
  '101 - Area Management',
  '102 - Package Coordination',
  '140 - Risk Management',
  '230 - Structural Engineering',
  '260 - Electrical Engineering',
  '270 - Systems and Process Control Engineering',
  '290 - Architecture',
  '300 - Procurement Management',
  '321 - Purchasing Formation',
  '322 - Purchasing Administration',
  '330 - Expediting',
  '340 - Vendor Quality Surveillance (incl. Inspection)',
  '350 - Logistics',
  '400 - Site Management, Construction Management, Construction Coordination',
  '403 - Construction Work Package Coordination',
  '411 - Health and Safety Management (including Permitting and Lockout)',
  '430 - Field Engineering',
  '432 - Civil Field Engineering',
  '433 - Structural Field Engineering',
  '434 - Mechanical Field Engineering',
  '435 - Piping Field Engineering',
  '436 - Electrical Field Engineering',
  '437 - Systems and Process Control Field Engineering',
  '440 - Construction Supervision',
  '454 - Site Laydown and Storage Areas',
  '460 - Site Contracts Administration',
  '471 - Site Planning and Scheduling',
  '473 - Site Cost Control',
  '480 - Site Project Services',
  '482 - Site Document Management',
  '486 - Site Administration (incl. travel/ accommodation)',
  '500 - Commissioning Management',
  '501 - Commissioning Planning',
  '503 - Commissioning Administration and Coordination (incl. handover admin, vendor coordination)',
  '511 - Pre-Operational Testing Process',
  '514 - Pre-Operational Testing Mechanical',
  '518 - Pre-Operational Testing Other',
  '601 - Periodic Reporting',
  '603 - Change Management',
  '610 - Planning and Scheduling',
  '620 - Cost Estimating',
  '630 - Cost Management',
  '640 - EPCM Services Control',
  '650 - Project Accounting',
  '700 - Project Services Management',
  '710 - Prime Contract Management',
  '720 - Document Management',
  '502 - Health and Safety Permit Coordination',
  '510 - Pre-Operational Testing',
  '516 - Pre-Operational Testing Electrical',
  '517 - Pre-Operational Testing Systems and Process Control',
  '410 - Site HSEC',
  '441 - Specialist Supervision',
  '442 - Civil Supervision',
  '443 - Structural Supervision',
  '444 - Mechanical Supervision',
  '445 - Piping Supervision',
  '446 - Electrical Supervision',
  '448 - Mining Supervision',
  '450 - Site Procurement and Materials Management',
  '451 - Site Warehousing',
  '455 - Site Logistics',
  '470 - Site Project Controls',
  '483 - Site Project Systems Management',
  '484 - Site Human Resources Management',
] as const

export const AREAS = [
  'Central Functions',
  'Process',
  'Head of Mining',
  'Mining',
  'NPI',
  'General',
  'NPI-Admin',
  'IPT',
  'Surface',
  'FE',
  'RET',
  'Mod Yard',
  'Surface Construction',
  'Project Site Mgmt',
  'Process - Wet Mill',
  'FE Mining',
] as const

export const SUB_AREAS = ['UG', 'SS', 'DV', 'Wet Mill'] as const

export const COUNTRIES = ['Canada', 'South Africa', 'India', 'Chile', 'USA'] as const

export const DISCIPLINES = [
  '10 - Project Management',
  '14 - Risk Management',
  '23 - Structural Engineering',
  '26 - Electrical Engineering',
  '27 - Systems and Process Control',
  '29 - Architecture',
  '30 - Procurement Management',
  '32 - Purchasing',
  '33 - Expediting',
  '34 - Vendor Quality Surveillance',
  '35 - Logistics',
  '40 - Construction Management',
  '41 - Site HSEC',
  '43 - Field Engineering',
  '44 - Construction Supervision',
  '45 - Site Procurement and Materials Management',
  '46 - Site Contracts Administration',
  '47 - Site Project Controls',
  '48 - Site Project Services',
  '50 - Commissioning Management',
  '51 - Pre-Operational Testing',
  '60 - Project Controls Management',
  '61 - Planning and Scheduling',
  '62 - Cost Estimating',
  '63 - Cost Management',
  '64 - EPCM Services Control',
  '65 - Project Accounting',
  '70 - Project Services Management',
  '71 - Prime Contract Management',
  '72 - Document Management',
] as const

export const POSITIONS = [
  'Human Resources Coordinator',
  'Area Manager - Dry Mill',
  'Package Coordinator–Process Area SMPEI',
  'Area Manager - Mining',
  'Package Coordinator',
  'Site Risk Specialist Mining',
  'Engineer',
  'Electrical Designer',
  'I&C Lead NPI Area',
  'PCS Lead',
  'I&C Package Engineer',
  'PCS Programmer',
  'Architectural Designer',
  'Architectural Lead',
  'Architect',
  'Intern Architect',
  'Purchasing Agent',
  'Materials Management Coordinator',
  'Expeditor - offsite',
  'Vendor Quality Surveillance Lead',
  'Logistics Lead',
  'Workforce Administrator',
  'SME Expert',
  'SME - Fire Load Study',
  'Mining - SME',
  'Package Coordinator - Product Storage',
  'Package Coordinator Product Handling',
  'Package Coordinator - Mining',
  'Training Lead JS1',
  'RET - Engineer - On Call',
  'Site Model Coordinator - Surface',
  'Blackline Coordinator',
  'Project Rigging Engineer',
  'RET - Rail Coordinator',
  'RET - Rail Systems Engineer',
  'RET - Structural',
  'RET - Structural Engineer',
  'RET-TRD6789-Structural Engneering',
  'Technical Support for Storage Bldg Constructability',
  'RET-TRD7360 - UG Steel Rework',
  'RET - Piping',
  'RET - Electrical',
  'RET - I&C',
  'Wayside Systems Engineer',
  'Completions Specialist',
  'Claims Lead',
  'Claims Specialist',
  'Mining Contracts Admin#3',
  'Mining Contracts Lead',
  'Site Contracts Administration Specialist',
  'Site Contracts Admn Analyst',
  'Site Services Contract Admin',
  'Claims Manager',
  'Mining Contracts Admin',
  'Contracts Administrator',
  'Mills Contracts Admin',
  'Storage Contracts Admin',
  'Contract Specialist',
  'Package Planner–Piling,Concrete,Buildings',
  'Commissioning and CVC Planner - NPI',
  'Package Planner – Raw Ore & Product',
  'Claims/Legacy CLose Out Cost Specialist',
  'Cost Controller - Lead',
  'Senior Cost Processing',
  'Cost Construction Mining',
  'Package Cost Specialist - Mod Yard',
  'Project Services Support',
  'Document Control Lead',
  'CMS - Transportation Coordinator',
  'Commissioning SME - Execution',
  'Commissioning SME - General',
  'Commissioning SME - Mechanical',
  'Commissioning SME – Mechanical',
  'Loadout Robots - Pre-Commissioning',
  'SME Surface',
  'Commissioning SME - Processing',
  'Commissioning Engineer - Mining',
  'Commissioning Engineer - Shafts',
  'Commissioning SME - Surface',
  'Commissioning Engineer',
  'Commissioning Engineer - Development',
  'Commissioning Engineer - Dry',
  'System Administrator',
  'Commissioning S&PC - Process',
  'Commissioning Engineer - Mechanical',
  'Commissioning Supervisor - S&PC',
  'Commissioning - S&PC',
  'Reporting and BI Specialist',
  'Change Coordinator',
  'Commissioning and CVC Planner - Mining',
  'General Planning & EOT Claim Support',
  'Senior Package Planner – Process/Mod Yards',
  'Package Planner – Shaft & Headframe',
  'Senior Cost Engineering Indirects',
  'Senior Cost – Mining',
  'Package Cost NPI BEA Cycle',
  'Package Cost - Mill',
  'Senior Cost Construction Processing',
  'Common Services & Commissioning Cost Specialist',
  'Cost Specialist',
  'QURR Coordinator',
  'System Superuser',
  'Project Accounting',
  'Project Accounting - EPCM Invoice',
  'Data Scientist',
  'Commercial Manager',
  'PAF and Staffing Coordinator',
  'Document Controller',
  'Project Support (PSG)',
  'Project Support Lead',
  'Commissioning Manager',
  'Deputy Commissioning Manager',
  'Handover & Services Lead',
  'Handover & Services Coodinator',
  'LOTO Authority Officer',
  'LOTO Coordinator - Surface',
  'LOTO Coordinator - Process',
  'LOTO Coordinator - Mine',
  'Commissioning Engineer - Wet',
  'Commissioning SME - Mineral Processing',
  'SME - Processing',
  'Lead Process',
  'Commissioning Engineer - Process',
  'Commissioning PCS',
  'Commissioning Lead Mechanical',
  'Commissioning Mechanical Process',
  'Commissioning Lead - Electrical Power Systems',
  'Commissioning Coordinator',
  'Commissioning Supervisor - Electrical Power Systems',
  'Commissioning Lead - S&PC',
  'Commissioning I&C Processing',
  'Commissioning Supervisor - Process',
  'Commissioning Engineer - Electrical Power Systems',
  'Commissioning Supervisor - E&I',
  'Commissioning Supervisor - Mechanical',
  'Commissioning Engineer - S&PC - Mining',
  'Commissioning I&C - Mining',
  'Deputy Project Director (Site)',
  'Project Construction Coordinator',
  'Head of Surface Construction',
  'Common Construction Services Superintendent',
  'Project Coordinator',
  'Package Coordinator - Dry Mill',
  'Package Coordinator - Wet Mill',
  'Package Specialist',
  'Safety Advisor NPI',
  'Safety Advisor Processing',
  'CCF - HSE Coordinator Orientations & Training 1',
  'CCF - HSE Coordinator Orientations & Training 3',
  'Safety Advisor Mining',
  'Lead Surface Safety',
  'Project Field Engineering Manager',
  'Raw Ore Product/Handling Storage Bldg Specialist',
  'Reality Capture Specialist',
  'RET - Engineering Lead',
  'Welding Specialist',
  'Raw Ore & Prod Handling/Storage Piping & Mechanical FE',
  'E&I Field Specialist',
  'Mining Deputy Technical Lead & E&I Specialist',
  'Mining E&I Specialist',
  'Night Shift Process Wet Piping/Mechanical Specialist',
  'Process Wet & Buildings/Infrastructure Depty TSC',
  'Raw Ore & Prod Handling/Storage Structural Steel Specialist',
  'Walk Down Specialist',
  'Walkdown Specialist M&P',
  'Night Shift Process Wet E&I FE',
  'Deputy Area Field Specialist',
  'Process Wet & Buildings/Infrastructure AFS',
  'Process Wet Structural Steel FS',
  'Mining Structural Steel Specialist',
  'RET - Mechanical',
  'M&P Field Specialist Mining',
  'Process Wet Piping & Mechanical Specialist',
  'Raw Ore & Prod Handling/Storage Deputy AFS',
  'Process Wet E&I FS',
  'Process Wet E&I Specialist',
  'Raw Ore & Prod Handling/Storage E&I FS',
  'Raw Ore & Prod Handling/Storage E&I Specialist',
  'Raw Ore & Prod Handling/Storage FL Lead',
  'RET - E&I',
  'Mining M&P Specialist',
  'Area Manager Product Handling',
  'Completions Coordinator',
  'Completions Manager',
  'Construction Lead',
  'Deputy Completions Manager',
  'Dry Mill Construction Elect & Inst NightShift SI',
  'Dry Mill Construction Elect & Inst SI',
  'Dry Mill Construction Lead',
  'Dry Mill Construction Manager',
  'Dry Mill Construction Mech/Piping NightShift SI',
  'Dry Mill Construction Mech/Piping Supervisor',
  'Electrical Power & Control Superintendent',
  'Mining Turnover Coordinator',
  'Process Turnover Coordinator',
  'Product Handling Construction Lead',
  'Product Handling Construction Superintendent',
  'Raw Ore & Product Storage Construction Structural SI',
  'Raw Ore & Product Storage E&I SI',
  'Raw Ore & Product Storage Night Shift SI',
  'Raw Ore / Product Storage Construction Manager',
  'Scaffolding Superintendent',
  'Turnover Coordinator',
  'Walkdown Specialist E&I',
  'Wet Mill Construction E&I Night Shift Superintendent',
  'Wet Mill Construction E&I Superintendent',
  'Wet Mill Construction Lead',
  'Wet Mill Construction Manager',
  'Wet Mill Construction Mech & Piping Night Shift SI',
  'Wet Mill Construction Mech & Piping SI',
  'Wet Mill Construction Piping Nightshift SI',
  'Wet Mill Construction Superintendent',
  'Electrical Superintendent',
  'Mining Construction Manager',
  'Mining Construction Superintendent',
  'Mining Coordinator',
  'Mining General Superintendent',
  'Principal Mining Construction',
  'Structural Superintendent',
  'Scaffolding Supervisor',
  'NPI - General Superintendent',
  'Raw Ore & Product Storage Construction Lead',
  'Mechanical Superintendent',
  'Deputy Raw Ore/Product Storage Construction Manager',
  'Dry Mill Construction Mech & Piping SI',
  'Principal Mine Ventilation',
  'Issuing Coordinator',
  'Material Management Coordinator - Mod Yard',
  'Material Management Coordinator - Product Storage',
  'Materials Manager',
  'Jansen Yard / Warehouse Lead',
  'Prevention & Maintenance Coordinator',
  'Material Management Coordinator - Surface',
  'Site Project Controls Manager',
  'Site Lead Planner',
  'Package Planner Processing',
  'Senior Planner',
  'Senior Cost Earthworks / Piling',
  'Site Systems Support Specialist',
  'Mining Systems Specialist',
  'Labour Relations Supervisor',
  'Site Human Resources Manager',
] as const

export const CLASSES = [
  'E12 - Junior Engineer',
  'E04 - Specialist/Supervisor',
  'E02 - Engineering, Project, Construction Manager',
  'E11 - Intermediate Engineer',
  'E09 - Senior Engineer',
  'W03 - Consultant - South Africa',
  'E14 - Senior Designer/Technician',
  'X11 - Intermediate Engineer - India',
  'X09 - Senior Engineer - India',
  'E03 - Consultant',
  'E13 - Technologist',
  'E15 - Designer/Technician',
  'W09 - Senior Engineer - South Africa',
  'E10 - Engineer',
  'W13 - Technologist - South Africa',
  'E17 - Junior Designer/Technician',
  'W14 - Senior Designer/Technician - South Africa',
  'E16 - Intermediate Designer/Technician',
  'E43 - Project Support Technician',
  'E01 - Senior Consultant',
  'E42 - Project Support Coordinator',
  'E24 - Technical Assistant',
  'X10 - Engineer - India',
  'E25 - Administrative Specialist',
  'X42 - Project Support Coordinator - India',
  'E00 - Principal',
] as const


export const ROSTERS = [
  'None',
  '5x2 (10 hrs)',
  'Change 10442',
  'TRFR TO WFR from Site Mar 31/26',
  '14X7 (10 hrs)',
  '14x7 (12 hrs)',
  '14x7 (10hrs) ',
  'TBD',
  'CAN/Site',
  '14x7 (12hrs)',
  '15x13 (11 hrs)',
  '15x13 (12 hrs)',
  '6x2 (10 hrs)',
  'Custom (10 hrs)',
  '8x6 (10 hrs)',
  '21x7 (10hrs)',
  '14x7 (10hrs)',
  '21x7 (10 hrs)',
  '10x4 (10hrs)',
] as const

export function sortAlpha<T extends string>(items: readonly T[]): T[] {
  return [...items].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
}
